# Site Settings
url: https://hongkuan-zhou.github.io/Homepage/
title: Hongkuan Zhou's Homepage
subtitle: ""
description: "Hongkuan's Homepage"
keywords: Hongkuan Zhou, 周泓宽
timezone: Europe/Berlin
encoding: "utf-8"
SEOTitle: Hongkuan Zhou's Homepage
repository: https://github.com/Hongkuan-Zhou/Homepage

# Author Settings
author: Hongkuan Zhou
github_username: Hongkuan-Zhou
location: Munich, Germany
email: hello.zhouhongkuan@gmail.com

# Navigation Settings
# navs:
#   -
#     href: 
#     label: Home

# RSS Settings
RSS: true
subscribe_rss: /feed.xml

# Build Settings
highlighter: rouge
paginate: 10
permalink: pretty
gems: [jekyll-paginate]
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
mathjax: true

# Comments Settings
comments_provider: gitment
gitment:
    owner: lpq29743
    repo: blog-comments
    oauth:
        client_id: 5818ceff784afe05d31c
        client_secret: dc7e8efc044c7194cf453740f82c646aa998f206
